name: version

on:
  push:
    branches: [dev]

permissions:
  contents: read

concurrency:
  group: version
  cancel-in-progress: false

jobs:
  propose:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        with:
          target-branch: dev
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
