name: version

on:
  push:
    branches: [dev]

permissions:
  contents: read

concurrency:
  group: version
  cancel-in-progress: false

jobs:
  propose:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@5c625bfb5d1ff62eadeeb3772007f7f66fdcf071 # v4.4.1
        with:
          target-branch: dev
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
